name: Redis Stack - Build & Deploy on DockerHub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          DOCKER_REPO_PATH=${{ secrets.DOCKER_HUB_USERNAME }}/redis-stack
          docker build -t $DOCKER_REPO_PATH:${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }} -t $DOCKER_REPO_PATH:${{ github.sha }} .
          docker push $DOCKER_REPO_PATH:${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
          docker push $DOCKER_REPO_PATH:${{ github.sha }}

      - name: Log out from Docker Hub
        run: docker logout